version: '3.8'

services:
  moody_api:
    build:
      context: .
      dockerfile: ./src/base/docker/Dockerfile
      args:
        PROJECT_DIR: ${PROJECT_DIR}
    container_name: moody_api
    ports:
      - "8080:8000"
    env_file: .env
    volumes:
      - ./src:$PROJECT_DIR
      - static_volume:$PROJECT_DIR/static
      - media_volume:$PROJECT_DIR/media
    command: >
      sh -c "python manage.py collectstatic --noinput &&
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000"
    networks:
      - moody_network

  celery_worker:
    build:
      context: .
      dockerfile: ./src/base/docker/Dockerfile
      args:
        PROJECT_DIR: ${PROJECT_DIR}
    container_name: celery_worker_container
    env_file: .env
    volumes:
      - ./src:$PROJECT_DIR
      - static_volume:$PROJECT_DIR/static
      - media_volume:$PROJECT_DIR/media
    command: >
      bash -c "celery -A base worker --loglevel=info"
    depends_on:
      - redis
      - moody_api
    networks:
      - moody_network

  flower:
    build:
      context: ./flower/
    image: flower2
    container_name: flower_container
    env_file: .env
    command: >
      bash -c "celery --broker=$CELERY_BROKER_URL flower --port=5555"
    volumes:
      - ./src:$PROJECT_DIR
      - static_volume:$PROJECT_DIR/static
      - media_volume:$PROJECT_DIR/media
    depends_on:
      - moody_api
      - celery_worker
      - redis
    ports:
      - "5555:5555"
    networks:
      - moody_network

  redis:
    image: redis:7-alpine
    container_name: moody_redis
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - moody_network

  db:
    image: postgres:15.3
    container_name: moody_postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file: .env
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    networks:
      - moody_network

volumes:
  static_volume:
  media_volume:
  redis_data:
  postgres_data:

networks:
  moody_network:
    driver: bridge
