# Generated by Django 4.2.5 on 2023-10-15 02:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube_id', models.CharField(max_length=255, unique=True)),
                ('youtube_url', models.CharField(max_length=255)),
                ('etag', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='YoutubeComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube_id', models.CharField(max_length=255, unique=True)),
                ('etag', models.CharField(blank=True, max_length=255)),
                ('text', models.TextField()),
                ('mood', models.BooleanField(default=None, null=True)),
                ('published_at', models.DateTimeField()),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='comments_analyzer.video')),
            ],
        ),
    ]
