# Generated by Django 4.2.5 on 2023-10-15 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments_analyzer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('ready_to_report', models.BooleanField(default=False)),
            ],
        ),
        migrations.RenameModel(
            old_name='Video',
            new_name='YoutubeVideo',
        ),
        migrations.RenameField(
            model_name='youtubevideo',
            old_name='youtube_id',
            new_name='video_id',
        ),
    ]
