# Generated by Django 4.2.5 on 2023-10-15 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments_analyzer', '0002_analysissession_rename_video_youtubevideo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubecomment',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
